config/routes.rb
Demo::Application.routes.draw do
  
  devise_for :users, path_names: {sign_in: 'login', sign_out: 'logout'}

  resources :microposts
  resources :users
  resources :blog_posts

  root to: 'users#index'
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  attr_accessible :content, :title, :user_id, :user

  validates :content, :title, :user_id, presence: true

  belongs_to :user
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content, :user_id, :image, :remote_image_url

  belongs_to :user

  validates :content, :length => { :maximum => 140 }

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
 # attr_accessible :email, :name

  has_many :microposts
  has_many :blog_posts

  def full_name
  	name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @blog_posts = BlogPost.order("created_at").page(params[:page]).per(5) #BlogPost.all
  end

  def show
    @blog_post = BlogPost.find(params[:id])
  end

  def new
    @blog_post = BlogPost.new
  end

 
  def edit
    @blog_post = BlogPost.find(params[:id])
  end

  def create
      @blog_post = BlogPost.new(params[:blog_post])
      if @blog_post.save
        redirect_to @blog_post, notice: 'Blog post was successfully created.'
      else
        render action: "new" 
      end
  end

  def update
      @blog_post = BlogPost.find(params[:id])

      if @blog_post.update_attributes(params[:blog_post])
        redirect_to @blog_post, notice: 'Blog post was successfully updated.'        
      else
        render action: "edit" 
      end
  end

  def destroy
    @blog_post = BlogPost.find(params[:id])
    @blog_post.destroy

    redirect_to blog_posts_url 
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @microposts = Micropost.order("created_at").page(params[:page]).per(5) #Micropost.all
  end

  def show
    @micropost = Micropost.find(params[:id])
  end

  def new
    @micropost = Micropost.new
  end

  def edit
    @micropost = Micropost.find(params[:id])
  end

  def create
      @micropost = Micropost.new(params[:micropost])

      if @micropost.save
        redirect_to @micropost, notice: 'Micropost was successfully created.' 
      else
        render action: "new" 
      end
  end

  def update
      @micropost = Micropost.find(params[:id])

      if @micropost.update_attributes(params[:micropost])
        redirect_to @micropost, notice: 'Micropost was successfully updated.' 
      else
        render action: "edit" 
      end
  end

  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy

    redirect_to microposts_url 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  
  def index
    @users = User.order("created_at").page(params[:page]).per(5)# User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
      @user = User.new(params[:user])

      if @user.save
        redirect_to @user, notice: 'User was successfully created.' 
      else
        render action: "new" 
      end
  end

  def update
      @user = User.find(params[:id])

      if @user.update_attributes(params[:user])
        redirect_to @user, notice: 'User was successfully updated.' 
      else
        render action: "edit" 
      end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_url 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post) do |f| %>
  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% @blog_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editing blog_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_post %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/index.html.erb
<h1>Listing blog_posts</h1>

<%= paginate @blog_posts %></br>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blog_posts.each do |blog_post| %>
  <tr>
    <td><%= blog_post.title %></td>
    <td><%= blog_post.content %></td>
    <td><%= blog_post.user.full_name %></td>
    <td><%= link_to 'Show', blog_post %></td>
    <td><%= link_to 'Edit', edit_blog_post_path(blog_post) %></td>
    <td><%= link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Blog post', new_blog_post_path %>

app/views/blog_posts/new.html.erb
<h1>New blog_post</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @blog_post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @blog_post.content %>
</p>

<p>
  <b>User:</b>
  <%= @blog_post.user_id %>
</p>


<%= link_to 'Edit', edit_blog_post_path(@blog_post) %> |
<%= link_to 'Back', blog_posts_path %>

app/views/layouts/_navigator.html.erb
<ul>
  <li><%= link_to "Home", root_path %></li>
</ul>

<ul>
  <li><%= link_to "Blog", blog_posts_path %></li>
</ul>

<ul>
  <li><%= link_to "Micropost", microposts_path %></li>
</ul>

app/views/layouts/application.html.erb
	<!DOCTYPE html>
<html>
	<head>
  		<title>Demo</title>
  		<%= stylesheet_link_tag    "application", :media => "all" %>
  		<%= javascript_include_tag "application" %>
  		<%= csrf_meta_tags %>
	</head>
	<body>
  		<div id="container">
			<div id="user_nav">
				<% if user_signed_in? %>
					Logged in as <strong><%= current_user.email %></strong>.
					<%= link_to 'Edit profile', edit_user_registration_path %>
					<%= link_to 'Logout', destroy_user_session_path, method: :delete %>
				<% else %>
					<%= link_to 'Registration', new_user_registration_path %>
					<%= link_to 'Login', new_user_session_path %>
				<% end %>			
			</div>		
			<%= render 'layouts/navigator' %>	
			<%= yield %>
  		</div>
	</body>
</html>

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :user_id %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :remote_image_url, "or image URL" %><br />
    <%= f.text_field :remote_image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<h1>Listing microposts</h1>

<%= paginate @microposts %></br>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th>Image</th>
    <th></th>
    <th></th>
  </tr>

<% @microposts.each do |micropost| %>
  <tr>
    <td><%= micropost.content %></td>
    <td><%= micropost.user_id %></td>
    <td><%= micropost.image %></td>
    <td><%= link_to 'Show', micropost %></td>
    <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
    <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @micropost.content %>
</p>

<p>
  <b>User:</b>
  <%= @micropost.user_id %>
</p>

<p>
  <b>Image:</b>
  <%= image_tag @micropost.image_url(:thumb).to_s %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<%= paginate @users %></br>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>